config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
end if Rails.env.production?

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/docs'
  mount Rswag::Api::Engine => '/docs'
  
  mount Sidekiq::Web => "/sidekiq"
  mount PgHero::Engine, at: "pghero"

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :jobs
      resources :collections, only: [:index, :show] do
        member do
          get :projects
        end
      end
      resources :projects, constraints: { id: /.*/ }, only: [:index, :show] do
        collection do
          get :lookup
        end
        member do
          get :ping
        end
      end
    end
  end

  resources :collections, only: [:index, :show] do
    member do
      get :committers
      get :committers_csv
    end
  end

  resources :projects, constraints: { id: /.*/ }, only: [:index, :show] do
    collection do
      post :lookup
    end
  end
  
  resources :exports, only: [:index], path: 'open-data'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  root "projects#index"
end

app/models/collection.rb
class Collection < ApplicationRecord
  include HttpClient
  validates :name, :url, presence: true

  has_many :projects

  def to_s
    name
  end

  def keywords
    projects.pluck(:keywords).flatten.group_by(&:itself).transform_values(&:count).sort_by{|k,v| v}.reverse
  end

  def committers
    projects.map(&:committers_names).flatten.group_by(&:itself).transform_values(&:count).sort_by{|k,v| v}.reverse
  end

  def educational_committers
    hash = Hash.new{|h,k| h[k] = 0}
    projects.map(&:educational_committers).each do |committers|
      committers.each do |k,v|
        hash[k] += v
      end
    end
    hash.sort_by{|k,v| v}.reverse
  end

  def educational_committers_emails
    hash = Hash.new{|h,k| h[k] = 0}
    projects.map(&:educational_committers_emails).each do |emails|
      emails.each do |k,v|
        hash[k] += v
      end
    end
    hash.sort_by{|k,v| v}.reverse
  end

  def educational_committers_email_domains
    hash = Hash.new{|h,k| h[k] = 0}
    projects.map(&:educational_committers_email_domains).each do |emails|
      emails.each do |k,v|
        hash[k] += v
      end
    end
    hash.sort_by{|k,v| v}.reverse
  end

  def committers_email_domains
    hash = Hash.new{|h,k| h[k] = 0}
    projects.map(&:committers_email_domains).each do |emails|
      emails.each do |k,v|
        hash[k] += v
      end
    end
    hash.sort_by{|k,v| v}.reverse
  end

  def committer_details
    committers = {}
    projects.each do |project|
      project.raw_committers.each do |committer|

        if committer['email'].match('@users.noreply.github.com') && !committer['email'].include?('[bot]')
          committer['login'] = committer['email'].gsub('@users.noreply.github.com', '').split('+').last
        end

        committer['bot'] = committer['name'].include?('[bot]') || committer['name'].downcase.ends_with?('bot') || committer['name'].downcase == 'github actions'

        committers[committer['name'].downcase] ||= committer
        committers[committer['name'].downcase]['login'] ||= committer['login']
        committers[committer['name'].downcase]['count'] ||= 0
        committers[committer['name'].downcase]['count'] += committer['count']
        committers[committer['name'].downcase]['projects'] ||= {}
        committers[committer['name'].downcase]['projects'][project.url] ||= 0
        committers[committer['name'].downcase]['projects'][project.url] += committer['count']
      end
    end
    committers.values.sort_by{|c| c['projects'].length}.reverse
  end

  def languages
    projects.map(&:language).flatten.group_by(&:itself).transform_values(&:count).sort_by{|k,v| v}.reverse
  end

  def commits
    hash = Hash.new{|h,k| h[k] = 0}
    projects.map(&:committers).each do |committers|
      committers.each do |k,v|
        hash[k] += v
      end
    end
    hash.sort_by{|k,v| v}.reverse
  end

  def committers_projects(name)
    projects.select{|p| p.committers_names.include?(name) }
  end

  def dependencies
    deps = projects.map(&:dependency_packages).flatten(1)
    deps.group_by(&:itself).transform_values(&:count).sort_by{|k,v| v}.reverse
  end

  def dependency_projects(dependency)
    projects.select{|p| p.dependency_packages.include?(dependency.split(':')) }
  end

  def owner_projects(owner)
    projects.select{|p| p.owner_name == owner }
  end

  def contributor_projects(contributor)
    projects.select{|p| p.contributors.keys.include?(contributor) }
  end

  def owners
    projects.map(&:owner_name).flatten.group_by(&:itself).transform_values(&:count).sort_by{|k,v| v}.reverse
  end

  def hosts
    projects.map(&:host).flatten.group_by(&:itself).transform_values(&:count).sort_by{|k,v| v}.reverse
  end

  def contributors
    combined_hash = Hash.new(0)
    
    projects.map(&:contributors).each do |contributors|
      contributors.each do |k,v|
        combined_hash[k] += v
      end
    end

    combined_hash.sort_by{|k,v| v}.reverse
  end

  def import_keyword(keyword)
    conn = build_faraday_connection("https://packages.ecosyste.ms/api/v1/keywords/#{keyword}?per_page=1000")
    resp = conn.get
    if resp.status == 200
      data = JSON.parse(resp.body)
      urls = data['packages'].reject{|p| p['status'].present? }.map{|p| p['repository_url'] }.uniq.reject(&:blank?)
      urls.each do |url|
        puts url
        project = projects.find_or_create_by(url: url)
        project.sync_async unless project.last_synced_at.present?
      end
    end
  end

  def import_topic(topic)
    conn = build_faraday_connection("https://repos.ecosyste.ms/api/v1/topics/#{topic}?per_page=1000")
    resp = conn.get
    if resp.status == 200
      data = JSON.parse(resp.body)
      urls = data['repositories'].map{|p| p['html_url'] }.uniq.reject(&:blank?)
      urls.each do |url|
        puts url
        project = projects.find_or_create_by(url: url)
        project.sync_async unless project.last_synced_at.present?
      end
    end
  end

  def import_org(host, org)
    conn = build_faraday_connection("https://repos.ecosyste.ms/api/v1/hosts/#{host}/owners/#{org}/repositories?per_page=1000")
    resp = conn.get
    if resp.status == 200
      data = JSON.parse(resp.body)
      urls = data.map{|p| p['html_url'] }.uniq.reject(&:blank?)
      urls.each do |url|
        puts url
        project = projects.find_or_create_by(url: url)
        project.sync_async unless project.last_synced_at.present?
      end
    end
  end

  def import_awesome_list(url)
    lookup_url = "https://awesome.ecosyste.ms/api/v1/lists/lookup?url=#{url}"
    conn = build_faraday_connection(lookup_url)
    resp = conn.get
    if resp.status == 200
      data = JSON.parse(resp.body)
      projects_url = data['projects_url'] + '?per_page=1000'
      conn2 = build_faraday_connection(projects_url)
      resp = conn2.get
      if resp.status == 200
        data = JSON.parse(resp.body)
        urls = data.map{|p| p['url'] }.uniq.reject(&:blank?)
        urls.each do |url|
          puts url
          project = projects.find_or_create_by(url: url)
          project.sync_async unless project.last_synced_at.present?
        end
      end
    end
  end

  def import_tag(tag)
    import_keyword(tag)
    import_topic(tag)
  end

  def remove_duplicate_projects
    projects.group_by(&:url).each do |url, projects|
      projects[1..-1].each(&:destroy)
    end
    return nil
  end

  def remove_uninteresting_forks
    projects.each do |project|
      if project.repository.present? && project.repository['source_name'].present? && project.repository['stargazers_count'] == 0
        puts "Removing #{project.url}"
        project.destroy
      end
    end
    return nil
  end
end

app/controllers/api/v1/collections_controller.rb
class Api::V1::CollectionsController < Api::V1::ApplicationController
  def index
    @collections = Collection.all
    @pagy, @collections = pagy(@collections)
  end

  def show
    @collection = Collection.find(params[:id])
  end

  def projects
    @collection = Collection.find(params[:id])
    @projects = @collection.projects.where.not(last_synced_at: nil)
    @pagy, @projects = pagy(@projects)
    render 'api/v1/projects/index'
  end
end

app/controllers/collections_controller.rb
require 'csv'
class CollectionsController < ApplicationController
  def show
    @collection = Collection.find(params[:id])

    scope = @collection.projects.with_repository.order('score desc').where.not(last_synced_at: nil)

    if params[:language].present?
      scope = scope.language(params[:language])
    end

    if params[:keyword].present?
      scope = scope.where("keywords @> ARRAY[?]::varchar[]", params[:keyword])
    end

    if params[:committer].present?
      scope = @collection.committers_projects(params[:committer])
    end

    if params[:dependency].present?
      scope = @collection.dependency_projects(params[:dependency])
    end

    if params[:owner].present?
      scope = @collection.owner_projects(params[:owner])
    end

    if params[:contributor].present? 
      scope = @collection.contributor_projects(params[:contributor])
    end

    if params[:language].present? || params[:keyword].present? || params[:committer].present? || params[:dependency].present? || params[:owner].present? || params[:contributor].present?
      @pagy, @projects = pagy_array(scope)
    else  
      @pagy, @projects = pagy_countless(scope)
    end
  end

  def committers
    @collection = Collection.find(params[:id])
    @pagy, @committers = pagy_array(@collection.committer_details)
  end

  def committers_csv
    @collection = Collection.find(params[:id])
    @committers = @collection.committer_details
    csv_string = CSV.generate do |csv|
      csv << ["Name", "Email", "GitHub", "Commits", "Unique Projects", "Projects", "Bot"]
      @committers.each do |committer|
        csv << [committer['name'], committer['email'], committer['login'], committer['count'], committer['projects'].length, committer['projects'].map(&:first).join(', '), committer['bot']]
      end
    end

    send_data csv_string, filename: "#{@collection.name}-committers.csv" , content_type: 'text/csv'
  end

  def index
    @scope = Collection.all
    @pagy, @collections = pagy(@scope)
  end
end

app/views/collections/_collection.html.erb
<div class="card mb-3 collection d-flex" id="collection_<%= collection.id %>">
  <div class="card-body pb-1">
    <div class="d-flex">
      
      <div class="flex-grow-1 ms-3 text-break">
        <h5 class='card-title'>
          <%= link_to collection, collection_path(collection) %>
        </h5>
      
        <p class="card-subtitle mb-2 text-muted">
          <%= collection.description %>
        </p>
        <p class="card-subtitle mb-2 text-muted">
          <i><small>
            <%= number_with_delimiter collection.projects.count %> projects
          </small></i>
        <p class="card-subtitle mb-2 text-muted"><i><small>
          Last updated: <%= collection.updated_at.strftime("%d %b %Y") %>
        </small></i></p>
      </div>
      <div class="flex-shrink-0">
        <%# todo avatar url %>
        <img src="" class="rounded" height='40' width='40' onerror="this.style.display='none'">
      </div>  
    </div>
  </div>
</div>

app/views/collections/committers.html.erb
<div class="container-md">
  <h1 class='mb-4'>
    <%= link_to 'Collections', collections_path %>:
    <%= link_to @collection.name, collection_path(@collection) %> - Committers
  </h1>

  <p class='text-muted'>
    <%= link_to 'Export all as CSV', committers_csv_collection_path(@collection) %>
  </p>

  <table class='table'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>GitHub</th>
        <th>Commits</th>
        <th>Unique Projects</th>
      </tr>
    </thead>
    <tbody>        
      <% @committers.each do |committer| %>
        <% next if committer['bot'] %>
        <tr>
          <td><%= committer['name'] %></td>
          <td><%= obfusticate_email committer['email']  %></td>
          <td><%= link_to_unless committer['login'].blank?, committer['login'], "https://github.com/#{committer['login']}" %></td>
          <td><%= committer['count'] %></td>
          <td><span title='<%= committer['projects'].sort_by(&:last).map(&:first).join(', ') %>'><%= committer['projects'].length %></span></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>  
</div>

app/views/collections/index.html.erb
<% @meta_title = "Collections" %>
<% @meta_description = "Collections of analysed open source software projects" %>

<div class="container-md">
  <ul class="nav nav-tabs mb-4">
    <li class="nav-item">
      <%= link_to 'Projects', projects_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Collections', collections_path, class: 'nav-link active' %>
    </li>
  </ul>
  
  <%= render @collections %>
  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>  
</div>

app/views/collections/show.html.erb
<% @meta_title = "#{@collection.name} collection" %>
<% @meta_description = "Collection of analysed open source software projects in the #{@collection.name} collection" %>

<div class="container-md">
  <h1 class='mb-4'>
    <%= link_to 'Collections', collections_path %>:
    <%= @collection.name %>
  </h1>

  <div class='row'>
    <div class='col-md-8'>
      <%= render @projects %>
      <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>  
    </div>
    <div class='col-md-4'>
      <% if @collection.projects.with_repository.count < 2000 %>
        <div class='card mb-3'>
          <div class="card-header">
            Keywords
          </div>
          <div class="list-group list-group-flush">
            <% @collection.keywords.first(30).each do |keyword, count| %>
              <% next if keyword.blank? %>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center <%= 'active' if keyword == params[:keyword]%>" href="<%= collection_path(@collection, keyword: keyword) %>">
                <%= keyword %>
                <span class="badge bg-primary rounded-pill"><%= number_with_delimiter count%></span>
              </a>
            <% end %>
          </div>
        </div>

        <div class='card mb-3'>
          <div class="card-header">
            Languages
          </div>
          <div class="list-group list-group-flush">
            <% @collection.languages.first(30).each do |keyword, count| %>
              <% next if keyword.blank? %>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center <%= 'active' if keyword == params[:language]%>" href="<%= collection_path(@collection, language: keyword) %>">
                <%= keyword %>
                <span class="badge bg-primary rounded-pill"><%= number_with_delimiter count%></span>
              </a>
            <% end %>
          </div>
        </div>

        <div class='card mb-3'>
          <div class="card-header">
            Most Issues and Pull Requests
          </div>
          <div class="list-group list-group-flush">
            <% @collection.contributors.first(30).each do |login, count| %>
              <% next if login.blank? %>
              
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center <%= 'active' if login == params[:contributor]%>" href="<%= collection_path(@collection, contributor: login) %>">
                <span>
                <img class="float-start me-2" src="https://github.com/<%= login %>.png" alt="<%= login %>" width='20' onerror="this.style.display='none'">
                <%= login %>
                </span>
                <span class="badge bg-primary rounded-pill" href='https://github.com/<%= login %>' target='_blank'><%= number_with_delimiter count%></span>
              </a>
            <% end %>
          </div>
        </div>

        <div class='card mb-3'>
          <div class="card-header">
            Committers
          </div>
          <div class="list-group list-group-flush">
            <% @collection.committers.first(30).each do |keyword, count| %>
              <% next if keyword.blank? %>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center <%= 'active' if keyword == params[:committer]%>" href="<%= collection_path(@collection, committer: keyword) %>">
                <%= keyword %>
                <span class="badge bg-primary rounded-pill" href='https://github.com/search?q=<%= keyword %>&type=users' target='_blank'><%= number_with_delimiter count%></span>
              </a>
            <% end %>
          </div>
        </div>

        <div class='card mb-3'>
          <div class="card-header">
            Most Commits
          </div>
          <div class="list-group list-group-flush">
            <% @collection.commits.first(30).each do |keyword, count| %>
              <% next if keyword.blank? %>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center <%= 'active' if keyword == params[:committer]%>" href="<%= collection_path(@collection, committer: keyword) %>">
                <%= keyword %>
                <span class="badge bg-primary rounded-pill" href='https://github.com/search?q=<%= keyword %>&type=users' target='_blank'><%= number_with_delimiter count%></span>
              </a>
            <% end %>
          </div>
        </div>

        <div class='card mb-3'>
          <div class="card-header">
            Direct Dependencies
          </div>
          <div class="list-group list-group-flush">
            <% @collection.dependencies.first(30).each do |keyword, count| %>
              <% next if keyword.blank? %>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center <%= 'active' if keyword.join(':') == params[:dependency]%>" href="<%= collection_path(@collection, dependency: keyword.join(':')) %>">
                <%= keyword.join ':' %>
                <span class="badge bg-primary rounded-pill"><%= number_with_delimiter count%></span>
              </a>
            <% end %>
          </div>
        </div>

        <div class='card mb-3'>
          <div class="card-header">
            Repository Owners
          </div>
          <div class="list-group list-group-flush">        
            <% @collection.owners.first(50).each do |owner, count| %>
              <% next if owner.blank? %>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center <%= 'active' if owner == params[:owner]%>" href="<%= collection_path(@collection, owner: owner) %>">
                <span>
                  <img class="float-start me-2" src="https://github.com/<%= owner %>.png" alt="<%= owner %>" width='20' onerror="this.style.display='none'">
                  <%= owner %>
                </span>
                
                <span class="badge bg-primary rounded-pill" href='https://github.com/<%= owner %>' target='_blank'><%= number_with_delimiter count%></span>
              </a>
            <% end %>
          </div>
        </div>

        <div class='card mb-3'>
          <div class="card-header">
            Repository Hosts
          </div>
          <div class="list-group list-group-flush">    
            <% @collection.hosts.first(50).each do |host, count| %>
              <% next if host.blank? %>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center <%= 'active' if host == params[:host]%>" href="<%= collection_path(@collection, host: host) %>">
                <%= host %>
                <span class="badge bg-primary rounded-pill"><%= number_with_delimiter count%></span>
              </a>
            <% end %>
          </div>
        </div>
      <% end %>  
    
      <div class='card'>
        <div class='card-body'>
          <h5 class='card-title'>Statistics</h5>
          <p class='card-text'>
            <ul>
              <li>
                Projects: <%= number_with_delimiter @collection.projects_count %>
              </li>
              <li>
                Last updated: <%= distance_of_time_in_words_to_now @collection.updated_at %> ago
              </li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>