config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
end if Rails.env.production?

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/docs'
  mount Rswag::Api::Engine => '/docs'
  
  mount Sidekiq::Web => "/sidekiq"
  mount PgHero::Engine, at: "pghero"

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :jobs
      resources :collections, only: [:index, :show] do
        member do
          get :projects
        end
      end
      resources :projects, constraints: { id: /.*/ }, only: [:index, :show] do
        collection do
          get :lookup
        end
        member do
          get :ping
        end
      end
    end
  end

  resources :collections, only: [:index, :show] do
    member do
      get :committers
      get :committers_csv
    end
  end

  resources :projects, constraints: { id: /.*/ }, only: [:index, :show] do
    collection do
      post :lookup
    end
  end
  
  resources :exports, only: [:index], path: 'open-data'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  root "projects#index"
end

app/models/project.rb
class Project < ApplicationRecord
  include HttpClient

  EDU_TLDS = %w[
    .edu
    .ac.uk
    .edu.au
    .ac.in
    .edu.cn
    .edu.sg
    .ac.jp
    .edu.co
    .ac.za
    .edu.mx
    .edu.my
    .ac.kr
    .edu.hk
    .ac.nz
    .ac.id
    .edu.ph
    .edu.br
    .ac.th
    .ac.ir
    .ac.il
  ]

  validates :url, presence: true

  belongs_to :collection, optional: true
  counter_culture :collection

  scope :language, ->(language) { where("(repository ->> 'language') = ?", language) }
  scope :owner, ->(owner) { where("(repository ->> 'owner') = ?", owner) }
  scope :with_repository, -> { where.not(repository: nil) }
  scope :with_issues, -> { where.not(issues: nil) }

  def self.sync_least_recently_synced
    Project.where(last_synced_at: nil).or(Project.where("last_synced_at < ?", 1.day.ago)).order('last_synced_at asc nulls first').limit(500).each do |project|
      project.sync_async
    end
  end

  def self.sync_all
    Project.all.each do |project|
      project.sync_async
    end
  end

  def to_s
    url
  end

  def sync
    check_url
    return unless self.persisted?
    fetch_repository
    fetch_owner
    fetch_dependencies
    fetch_packages
    combine_keywords
    fetch_commits
    fetch_events
    fetch_issues
    fetch_publiccode_yml
    fetch_codemeta_json
    update(last_synced_at: Time.now)
    update_score
    ping
  end

  def sync_async
    SyncProjectWorker.perform_async(id)
  end

  def check_url
    conn = build_faraday_connection(url)

    response = conn.get
    return unless response.success?

    new_name = response.env.url.to_s
    return if new_name == url
    existing_projects = Project.where(url: new_name)
    if existing_projects.present?
      self.destroy
    else
      update(url: response.env.url.to_s) 
    end
  rescue
    # failed to load
  end

  def combine_keywords
    keywords = []
    keywords += repository["topics"] if repository.present?
    keywords += packages.map{|p| p["keywords"]}.flatten if packages.present?
    self.keywords = keywords.uniq.reject(&:blank?)
    self.save
  end

  def ping
    ping_urls.each do |url|
      conn = build_faraday_connection(url)
      conn.get rescue nil
    end
  end

  def ping_urls
    ([repos_ping_url] + packages_ping_urls + [owner_ping_url]).compact.uniq
  end

  def repos_ping_url
    return unless repository.present?
    "https://repos.ecosyste.ms/api/v1/hosts/#{repository['host']['name']}/repositories/#{repository['full_name']}/ping"
  end

  def packages_ping_urls
    return [] unless packages.present?
    packages.map do |package|
      ["https://packages.ecosyste.ms/api/v1/registries/#{package['registry']['name']}/packages/#{package['name']}/ping",
      "https://repos.ecosyste.ms/api/v1/usage/#{package['ecosystem']}/#{package['name']}/ping"]
    end.flatten
  end

  def owner_ping_url
    return unless repository.present?
    "https://repos.ecosyste.ms/api/v1/hosts/#{repository['host']['name']}/owner/#{repository['owner']}/ping"
  end

  def description
    return unless repository.present?
    repository["description"]
  end

  def repos_url
    "https://repos.ecosyste.ms/api/v1/repositories/lookup?url=#{url}"
  end

  def fetch_repository
    conn = build_faraday_connection(repos_url)

    response = conn.get
    return unless response.success?
    self.repository = JSON.parse(response.body)
    self.save
  rescue
    puts "Error fetching repository for #{url}"
  end

  def owner_url
    return unless repository.present?
    return unless repository["owner"].present?
    return unless repository["host"].present?
    return unless repository["host"]["name"].present?
    "https://repos.ecosyste.ms/api/v1/hosts/#{repository['host']['name']}/owners/#{repository['owner']}"
  end

  def fetch_owner
    return unless owner_url.present?
    conn = build_faraday_connection(owner_url)

    response = conn.get
    return unless response.success?
    self.owner = JSON.parse(response.body)
    self.save
  rescue
    puts "Error fetching owner for #{url}"
  end

  def timeline_url
    return unless repository.present?
    return unless repository["host"]["name"] == "GitHub"

    "https://timeline.ecosyste.ms/api/v1/events/#{repository['full_name']}/summary"
  end

  def fetch_events
    return unless timeline_url.present?
    conn = build_faraday_connection(timeline_url)

    response = conn.get
    return unless response.success?
    summary = JSON.parse(response.body)

    conn = build_faraday_connection(timeline_url+'?after='+1.year.ago.to_fs(:iso8601))

    response = conn.get
    return unless response.success?
    last_year = JSON.parse(response.body)

    self.events = {
      "total" => summary,
      "last_year" => last_year
    }
    self.save
  rescue
    puts "Error fetching events for #{url}"
  end

  # TODO fetch repo dependencies
  # TODO fetch repo tags

  def packages_url
    "https://packages.ecosyste.ms/api/v1/packages/lookup?repository_url=#{url}"
  end

  def fetch_packages
    conn = build_faraday_connection(packages_url)

    response = conn.get
    return unless response.success?
    self.packages = JSON.parse(response.body)
    self.save
  rescue
    puts "Error fetching packages for #{url}"
  end

  def commits_api_url
    "https://commits.ecosyste.ms/api/v1/repositories/lookup?url=#{url}"
  end

  def commits_url
    "https://commits.ecosyste.ms/repositories/lookup?url=#{url}"
  end

  def fetch_commits
    conn = build_faraday_connection(commits_api_url)
    response = conn.get
    return unless response.success?
    self.commits = JSON.parse(response.body)
    self.save
  rescue
    puts "Error fetching commits for #{url}"
  end

  def committers_names
    return [] unless commits.present?
    return [] unless commits["committers"].present?
    commits["committers"].map{|c| c["name"].downcase }.uniq
  end

  def committers
    return [] unless commits.present?
    return [] unless commits["committers"].present?
    commits["committers"].map{|c| [c["name"].downcase, c["count"]]}.each_with_object(Hash.new {|h,k| h[k] = 0}) { |(x,d),h| h[x] += d }
  end

  def committers_emails
    return [] unless commits.present?
    return [] unless commits["committers"].present?
    commits["committers"].map{|c| [c["email"].downcase, c["count"]]}.each_with_object(Hash.new {|h,k| h[k] = 0}) { |(x,d),h| h[x] += d }
  end

  def committers_email_domains
    return [] unless commits.present?
    return [] unless commits["committers"].present?
    commits["committers"].map{|c| [c["email"].downcase.split('@').last, c["count"]]}.each_with_object(Hash.new {|h,k| h[k] = 0}) { |(x,d),h| h[x] += d }
  end  

  def educational_email?(email)
    EDU_TLDS.any? { |tld| email.end_with?(tld) }
  end

  def educational_commits_percentage
    return 0 unless commits.present?
    return 0 unless commits["committers"].present?
    total = commits["committers"].map{|c| c["count"]}.sum
    return 0 if total == 0
    educational = commits["committers"].select{|c| c["email"].present? && educational_email?(c["email"].downcase) }.map{|c| c["count"]}.sum
    (educational.to_f / total) * 100
  end

  def educational_committers
    return [] unless commits.present?
    return [] unless commits["committers"].present?
    commits["committers"].select{|c| c["email"].present? && educational_email?(c["email"].downcase) }.map{|c| [c["name"].downcase, c["count"]]}.each_with_object(Hash.new {|h,k| h[k] = 0}) { |(x,d),h| h[x] += d }
  end
  
  def educational_committers_emails
    return [] unless commits.present?
    return [] unless commits["committers"].present?
    commits["committers"].select{|c| c["email"].present? && educational_email?(c["email"].downcase) }.map{|c| [c["email"].downcase, c["count"]]}.each_with_object(Hash.new {|h,k| h[k] = 0}) { |(x,d),h| h[x] += d }
  end
  
  def educational_committers_email_domains
    return [] unless commits.present?
    return [] unless commits["committers"].present?
    commits["committers"].select{|c| c["email"].present? && educational_email?(c["email"].downcase) }.map{|c| [c["email"].downcase.split('@').last, c["count"]]}.each_with_object(Hash.new {|h,k| h[k] = 0}) { |(x,d),h| h[x] += d }
  end

  def raw_committers
    return [] unless commits.present?
    return [] unless commits["committers"].present?
    commits["committers"]
  end

  def contributors
    return [] unless issues.present?
    
    combined_authors = issue_authors.merge(pull_request_authors) do |key, oldval, newval|
      oldval + newval
    end
    
    combined_authors
  end

  def issue_authors
    return {} unless issues.present?
    return {} unless issues.issue_authors.present?
    issues.issue_authors.to_h.map{|k,v| [k.downcase.to_s, v] }.to_h
  end

  def pull_request_authors
    return {} unless issues.present?
    return {} unless issues.pull_request_authors.present?
    issues.pull_request_authors.to_h.map{|k,v| [k.downcase.to_s, v] }.to_h
  end

  def fetch_dependencies
    return unless repository.present?
    conn = build_faraday_connection(repository['manifests_url'])
    response = conn.get
    return unless response.success?
    self.dependencies = JSON.parse(response.body)
    self.save
  rescue
    puts "Error fetching dependencies for #{url}"
  end

  def dependency_packages
    return [] unless dependencies.present?
    dependencies.map{|d| d["dependencies"]}.flatten.select{|d| d['direct'] }.map{|d| [d['ecosystem'],d["package_name"]]}.uniq
  end

  def fetch_dependent_repos
    return unless packages.present?
    dependent_repos = []
    packages.each do |package|
      # TODO paginate
      # TODO group dependencies by repo
      dependent_repos_url = "https://repos.ecosyste.ms/api/v1/usage/#{package["ecosystem"]}/#{package["name"]}/dependencies"
      conn = build_faraday_connection(dependent_repos_url)
      response = conn.get
      return unless response.success?
      dependent_repos += JSON.parse(response.body)
    end
    self.dependent_repos = dependent_repos.uniq
    self.save
  end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::ApplicationController
  def index
    @projects = Project.all.where.not(last_synced_at: nil)
    @pagy, @projects = pagy(@projects)
  end

  def show
    @project = Project.find(params[:id])
  end

  def lookup
    @project = Project.find_by(url: params[:url])
    if @project.nil?
      @project = Project.create(url: params[:url])
      @project.sync_async
    end
    @project.sync_async if @project.last_synced_at.nil? || @project.last_synced_at < 1.day.ago
  end

  def ping
    @project = Project.find(params[:id])
    @project.sync_async
    render json: { message: 'pong' }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
  end

  def index
    @scope = Project.all.where.not(last_synced_at: nil).where.not(repository: nil).order('created_at DESC')
    @pagy, @projects = pagy(@scope)
  end

  def lookup
    @project = Project.find_by(url: params[:url].strip)
    if @project.nil?
      @project = Project.create(url: params[:url].strip)
      @project.sync_async
    end
    redirect_to @project
  end
end

app/views/projects/_committers.html.erb
<% if @project.commits && @project.commits['last_synced_at'] %>
    <hr>
    <h2>
      Committers metadata
    </h2>

    <% if @project.commits['last_synced_at'] %>
      <p class="card-subtitle mb-2 text-muted"><i><small>
        Last synced: <%= distance_of_time_in_words_to_now @project.commits['last_synced_at'] %> ago
    </small></i></p>
    <% end %>
    <% if @project.commits['total_commits'] %>
      <div class='row'>
        <div class='col-md-6'>
          <p>
            Total Commits: <%= number_with_delimiter @project.commits['total_commits'] %><br>
            Total Committers: <%= number_with_delimiter @project.commits['total_committers'] %><br>
            Avg Commits per committer: <%= number_with_delimiter @project.commits['mean_commits'].round(3) %><br>
            Development Distribution Score (<a href='https://report.opensustain.tech/chapters/development-distribution-score.html' target="_blank">DDS</a>): <%= @project.commits['dds'].round(3) %><br/>
          </p>
        </div>
        <div class='col-md-6'>
          <% if @project.commits['past_year_total_commits'] %>
            <p>
              Commits in past year: <%= number_with_delimiter @project.commits['past_year_total_commits'] %><br>
              Committers  in past year: <%= number_with_delimiter @project.commits['past_year_total_committers'] %><br>
              Avg Commits per committer in past year: <%= number_with_delimiter @project.commits['past_year_mean_commits'].round(3) %><br>
              Development Distribution Score (<a href='https://report.opensustain.tech/chapters/development-distribution-score.html' target="_blank">DDS</a>)  in past year: <%= @project.commits['past_year_dds'].round(3) %><br/>
            </p>
          <% end %>
        </div>
      </div>

    <table class='table'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Commits</th>
        </tr>
      </thead>
      <tbody>        
        <% @project.commits['committers'].first(30).each do |committer| %>
          <tr>
            <td><%= link_to_unless committer['login'].blank?, committer['name'], "https://github.com/#{committer['login']}" %></td>
            <td><%= obfusticate_email(committer['email']) %></td>
            <td><%= committer['count'] %></td>
          </tr>
        <% end %>
        <% if @project.commits['total_committers'] > 30 %>
          <tr>
            <td colspan='3'>
              <i>
              and <a href='<%= @project.commits_url %>'><%= @project.commits['total_committers'] - 30 %> more...</a>
              </i>
            </td>
          </tr>
        <%end %>
      </tbody>
    </table>
    <% end %>

  <% end %>

app/views/projects/_dependencies.html.erb
<% if @project.dependencies.present? %>
  <hr/>
  <h2>Dependencies</h2>

  <% @project.dependencies.each do |manifest| %>
    <div class="card mb-3">
      <div class="card-header">
        <%= manifest['filepath'] %>
        <span class='text-muted'>
          <%= manifest['ecosystem'] %>
        </span>
      </div>
      <ul class="list-group list-group-flush">
        <% if manifest['kind'] == 'lockfile' && manifest['dependencies'].length > 100 %>
          <li class="list-group-item">
            <%= pluralize(manifest['dependencies'].length, 'dependencies') %>
          </li>
        <% else %>
          <% manifest['dependencies'].sort_by{|d| [d['kind'], d['package_name']]}.each do |dependency| %>
            <li class="list-group-item">
              <%= dependency['package_name'] %>
              <i><%= dependency['requirements'] %></i>
              <small class='text-muted'>
              <% if dependency['kind'] != 'runtime' %>
                <%= dependency['kind'] %>
              <% end %>
              <% if dependency['optional'] %>
                (optional)
              <% end %>
              </small>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/projects/_events.html.erb
<% if @project.events %>
  <hr>
  <h2>
    GitHub Events
  </h2>
  
  <h5>Total</h5>
  <ul>
    <% @project.events['total'].sort_by{|k,v| k}.each do |k,v| %>
      <li>
        <%= k.underscore.humanize %>: <%= v %>
      </li>
    <% end %>
    <li>
      Total: <%= @project.events['total'].sum{|k,v| v} %>
    </li>
  </ul>
  <h5>Last Year</h5>
  <ul>
    <% @project.events['last_year'].sort_by{|k,v| k}.each do |k,v| %>
      <li>
        <%= k.underscore.humanize %>: <%= v %>
      </li>
    <% end %>
    <li>
      Total: <%= @project.events['last_year'].sum{|k,v| v} %>
    </li>
  </ul>
<% end %>

app/views/projects/_issues.html.erb
<% if @project.issues && @project.issues['last_synced_at'] %>

    <hr>
    <h2>
      Issue and Pull Request metadata
    </h2>

  <% if @project.issues['last_synced_at'] %>
      <p class="card-subtitle mb-2 text-muted"><i><small>
        Last synced: <%= distance_of_time_in_words_to_now @project.issues['last_synced_at'] %> ago
    </small></i></p>
    <% end %>
    <% if @project.issues['issues_count'] %>
      <div class='row'>
        <div class='col-md-6'>
          <p>
            Total issues: <%= number_with_delimiter @project.issues.issues_count %><br>
            Total pull requests: <%= number_with_delimiter @project.issues.pull_requests_count %><br>
            Average time to close issues: <%= distance_of_time_in_words_if_present @project.issues.avg_time_to_close_issue %><br>
            Average time to close pull requests: <%= distance_of_time_in_words_if_present @project.issues.avg_time_to_close_pull_request %><br>
            Total issue authors: <%= number_with_delimiter @project.issues.issue_authors_count %><br>
            Total pull request authors: <%= number_with_delimiter @project.issues.pull_request_authors_count %><br>
            Average comments per issue: <%= rounded_number_with_delimiter @project.issues.avg_comments_per_issue %><br>
            Average comments per pull request: <%= rounded_number_with_delimiter @project.issues.avg_comments_per_pull_request %><br>
            Merged pull request: <%= rounded_number_with_delimiter @project.issues.merged_pull_requests_count %><br>

            Bot issues: <%= number_with_delimiter @project.issues.bot_issues_count %><br>
            Bot pull requests: <%= number_with_delimiter @project.issues.bot_pull_requests_count %>
          </p>
        </div>
        <div class='col-md-6'>
          <p>
            Past year issues: <%= number_with_delimiter @project.issues.past_year_issues_count %><br>
            Past year pull requests: <%= number_with_delimiter @project.issues.past_year_pull_requests_count %><br>
            Past year average time to close issues: <%= distance_of_time_in_words_if_present @project.issues.past_year_avg_time_to_close_issue %><br>
            Past year average time to close pull requests: <%= distance_of_time_in_words_if_present @project.issues.past_year_avg_time_to_close_pull_request %><br>
            Past year issue authors: <%= number_with_delimiter @project.issues.past_year_issue_authors_count %><br>
            Past year pull request authors: <%= number_with_delimiter @project.issues.past_year_pull_request_authors_count %><br>
            Past year average comments per issue: <%= rounded_number_with_delimiter @project.issues.past_year_avg_comments_per_issue %><br>
            Past year average comments per pull request: <%= rounded_number_with_delimiter @project.issues.past_year_avg_comments_per_pull_request %><br>
            Past year merged pull request: <%= rounded_number_with_delimiter @project.issues.past_year_merged_pull_requests_count %><br>
            Past year bot issues: <%= number_with_delimiter @project.issues.past_year_bot_issues_count %><br>
            Past year bot pull requests: <%= number_with_delimiter @project.issues.past_year_bot_pull_requests_count %>
        </div>
      </div>
      More stats: <%= link_to @project.issues_url, @project.issues_url, target: :_blank %><br>
      <hr>
      <% if @project.issues.issue_author_associations_count.any? || @project.issues.pull_request_author_associations_count.any? %>
      <div class='row'>
        <div class='col-md-4'>
          <h4>Issue Author Associations</h4>
          <ul>
            <% @project.issues.issue_author_associations_count.each do |author, count| %>
              <li>
                <%= author.humanize %>
                (<%= number_with_delimiter count %>, <%= number_to_percentage count.to_f / @project.issues.issues_count * 100, precision: 2 %>)
              </li>
            <% end %>
          </ul>
        </div>
        <div class='col-md-4'>
          <h4>Pull Request Author Associations</h4>
          <ul>
            <% @project.issues.pull_request_author_associations_count.each do |author, count| %>
              <li>
                <%= author.humanize %>
                (<%= number_with_delimiter count %>, <%= number_to_percentage count.to_f / @project.issues.pull_requests_count * 100, precision: 2 %>)
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <hr>
      <% end %>
      <div class='row'>
        <div class='col-md-4'>
          <h4>Top Issue Authors</h4>
          <ul>
            <% @project.issues.issue_authors.to_h.first(15).each do |author, count| %>
              <li>
                <%= author %>
                (<%= number_with_delimiter count %>)
              </li>
            <% end %>
          </ul>
        </div>
        <div class='col-md-4'>
          <h4>Top Pull Request Authors</h4>
          <ul>
            <% @project.issues.pull_request_authors.to_h.first(15).each do |author, count| %>
              <li>
                <%= author %>
                (<%= number_with_delimiter count %>)
              </li>
            <% end %>
          </ul>
        </div>
      </div>

      <hr>
      <div class='row'>
        <div class='col-md-4'>
          <h4>Top Issue Labels</h4>
          <ul>
            <% @project.issues.issue_labels_count.to_h.first(30).each do |label, count| %>
              <li>
                <%= label %>
                (<%= number_with_delimiter count %>)
              </li>
            <% end %>
          </ul>
        </div>
        <div class='col-md-4'>
          <h4>Top Pull Request Labels</h4>
          <ul>
            <% @project.issues.pull_request_labels_count.to_h.first(30).each do |label, count| %>
              <li>
                <%= label %>
                (<%= number_with_delimiter count %>)
              </li>
            <% end %>
          </ul>
        </div>
      </div>

    <% end %>
<% end %>

app/views/projects/_owner.html.erb
<% if @project.owner %>
  <hr>
  <h2>
    Owner metadata: 
  </h2>

  <ul>
    <li>
      Name: <%= @project.owner['name'] %>
    </li>
    <li>
      Login: <%= @project.owner['login'] %>
    </li>
    <li>
      Email: <%= @project.owner['email'] %>
    </li>
    <li>
      Kind: <%= @project.owner['kind'] %>
    </li>
    <li>
      Description: <%= @project.owner['description'] %>
    </li>
    <li>
      Website: <%= @project.owner['website'] %>
    </li>
    <li>
      Location: <%= @project.owner['location'] %>
    </li>
    <li>
      Twitter: <%= @project.owner['twitter'] %>
    </li>
    <li>
      Company: <%= @project.owner['company'] %>
    </li>
    <li>
      Icon url: <%= @project.owner['icon_url'] %>
    </li>
    <li>
      Repositories: <%= @project.owner['repositories_count'] %>
    </li>
    <li>
      Last Synced at: <%= @project.owner['last_synced_at'] %>
    </li>
    <li>
      Profile URL: <%= @project.owner['html_url'] %>
    </li>
  </ul>
<% end %>

app/views/projects/_project.html.erb
<div class="card mb-3 project d-flex" id="project_<%= project.id %>">
  <div class="card-body pb-1">
    <div class="d-flex">
      
      <div class="flex-grow-1 ms-3 text-break">
        <h5 class='card-title'>
          <%= link_to project, project_path(project) %>
        </h5>
      
        <p class="card-subtitle mb-2 text-muted">
          <%= project.description %>
        </p>

        <% if project.keywords.any? %>
          <p>
            <% project.keywords.each do |keyword| %>
              <span class="badge bg-light text-dark">
                <%= keyword %>
              </span>
            <% end %>
          </p>
        <% end %>

        <p class="card-subtitle mb-2 text-muted"><i><small>
          Last synced: <%= project.last_synced_at.strftime("%d %b %Y") %>
        </small></i></p>
      </div>
      <div class="flex-shrink-0">
        <img src="<%= project.avatar_url %>" class="rounded" height='40' width='40' onerror="this.style.display='none'">
      </div>  
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="col-lg-4 container-md text-center">
  <form class="row g-2 justify-content-center" action='<%= lookup_projects_path %>' method="post">
    <div class="col-auto">
      <label for="repo_name" class="visually-hidden">Project URL</label>
      <input name='url' type="text" class="form-control" id="url" placeholder="URL: eg https://github.com/ecosyste-ms/packages" size="50">
    </div>
    <div class="col-auto">
      <button type="submit" class="btn btn-primary mb-3">Summarize</button>
    </div>
  </form>
</div>

<div class="container-md">
  <ul class="nav nav-tabs mb-4">
    <li class="nav-item">
      <%= link_to 'Projects', projects_path, class: 'nav-link active' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Collections', collections_path, class: 'nav-link ' %>
    </li>
  </ul>

  <%= render @projects %>
  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>  
</div>

app/views/projects/show.html.erb
<% @meta_title = "#{@project.url} summary" %>
<% @meta_description = "Summary of the open source software project at #{@project.url}" %>

<div class="container-md">
  <h1>
    <% if @project.collection %>
      <%= link_to @project.collection, collection_path(@project.collection) %>:
    <% end %>
    <%= @project.url %>
  </h1>

  <% if @project.last_synced_at %>
  
    <% if @project.keywords.any? %>
      <p>
        <% @project.keywords.each do |keyword| %>
          <span class="badge bg-light text-dark">
            <%= keyword %>
          </span>
        <% end %>
      </p>
    <% end %>

    <p>
      Score: <%= @project.score %>
    </p>

    <p class="card-subtitle mb-2 text-muted"><i><small>
        Last synced: <%= distance_of_time_in_words_to_now @project.last_synced_at %> ago <br>
        <%= link_to 'JSON representation', api_v1_project_path(@project) %>
    </small></i></p>

    <%= render 'repository' %>
    <%= render 'owner' %>
    <%= render 'events' %>
    <%= render 'committers' %>
    <%= render 'issues' %>
    <%= render 'packages' %>
    <%= render 'dependencies' %>

  <% else %>
    <p>
      This project has not been synced yet. Check back in a few minutes.
    </p>
  <% end %>

</div>